### ISSUE TITLE
webpack file-loader: file not found in bundle, but file exists where/as expected upon build

### ISSUE THREAD

**Issue by ddaaggeett** [ddaaggeett/podware#1]
i'm using [file-loader](https://github.com/webpack-contrib/file-loader) with webpack 4

in one of my `react.jsx` files, i call an image module: `<img src={require(../relative/path/images/image.png)} />` and after building with webpack, the asset gets bundled (as expected) to an `image.png` file in the `build/images/` directory.

after the build, i can see the `image.png` file itself bundled to the exact location i'm intending, yet my browser is spitting out to me the error:
```
GET file:///build/images/image.png
net::ERR_FILE_NOT_FOUND
/build/images/image.png:1
```
the bundled assets even display in the webpack output contained in the `build/` public directory:
```
...
                Asset       Size  Chunks             Chunk Names
     images/image.png   39.6 KiB          [emitted]
            bundle.js    631 KiB    main  [emitted]  main
           bundle.css  513 bytes    main  [emitted]  main
...
```
here's the relevant portion of my `webpack.config.js` file
```
module.exports = {
    ...
    output: {
        path: path.resolve(__dirname, 'build'),
        publicPath: '/build/',
        filename: 'bundle.js'
    },
    module: {
        rules: [
            ...
            {
                test: /\.(png|jpg)$/,
                use: [
                    {
                        loader: 'file-loader',
                        query: {
                            name: '[name].[ext]',
                            publicPath: '/build/',
                            outputPath: 'images/',
                        }
                    }
                ]                
            }
            ...
        ]
    ...
    }
}
```
i've read the webpack documentation on [bundling output files](https://webpack.js.org/configuration/output/) pertaining to the basics i require and have exhausted tutorials on loading image files using file-loader, but for the life of me cannot get the image file loading in the browser.

please help!
i can only imagine the godsend if @sokra or @d3viant0ne themselves went out of their way to spark/share this issue :)

**Comment by ddaaggeett** [comment]
so this may seem petty now, but i fixed this issue by using [url-loader](https://webpack.js.org/loaders/url-loader/) instead of file-loader. would anyone know why this to be the soluble case?

**Comment by sshapoval** [comment]
Hi! @ddaaggeett,
I have the same issue, how do you solve it with url-loader?

**Comment by ddaaggeett** [comment]
hi, @sshapoval,
i ended up simply using the url-loader like so in [`webpack.config.js`](https://github.com/ddaaggeett/podware/blob/master/webpack.config.js)
```
...
    module: {
        rules: [
            ...
            { 
                test: /\.(png|jpg)$/,
                use: 'url-loader'
            }
            ...
        ]
    },
...
```
then in my `component.jsx`, my image file is rendered like so:
```
<img src={require('../relative/path/to/image.png')} />
```
